-- ====================================================================
-- CharactersTracker Locale
-- ====================================================================

-- 1. 获取当前游戏客户端语言
local currentLocale = GetLocale()

-- 2. 默认语言包（基准语言，如果找不到对应语言则隐式继承英文，防止报错空指针）
local L = setmetatable({}, {
  __index = function(t, k)
    return k -- 如果某个词条没翻译，直接返回键名本身
  end
})

-- 注册全局或 addon 内部局部变量（这里我们直接绑定到 L 方便调用）
CharactersTracker_Locale = L
L["CT_TITLE"] = "Characters Tracker"
L["FB_FUNC"] = "Warband Characters Tracker"
L["FB_L1"] = "Hold Left-Click: Drag to reposition button"
L["FB_L2"] = "Left-Click: Toggle Warband Character List"
L["FB_L3"] = "Right-Click: Toggle Warband Inventory Summary"
L["VT_TITLE"] = "Great Vault Weekly Progress"
L["VT_RAIDS"] = "Raids"
L["VT_DUNGEONS"] = "Dungeons"
L["VT_DW"] = "Delves/World"
L["VT_UNLOCKED"] = "Unlocked"
L["VT_LEVEL"] = "Tier %d"
L["VT_LOCKED"] = "N/A"
L["CHOOSE_CHARACTER"] = "Characters"
L["GEAR_DETAIL"] = "Gear Detail"
L["CURR_TIP_L1"] = "No local currency data available"
L["CURR_TIP_L2"] = "Log in to this character to sync"
L["CURR_WEEKLY_LIMIT"] = " |cff0070dd(%d/%d) Weekly|r"
L["CURR_SEASON_LIMIT"] = " |cffff8000(%d/%d) Season|r"
L["CURR_LIMIT"] = " |cffffd100(%d/%d)|r"
L["INV_TITLE"] = "Inventory Summary"
L["INV_LOADING"] = "Loading..."
L["INV_SEARCH_TIP"] = "Search..."
L["INV_DETAIL"] = "|cffffd100Inventory Detail:|r"
L["INV_SRC_WARBAND"] = "|cff66bbffWarband|r"
L["INV_LOC_BAG"] = "Bag"
L["INV_LOC_REAGENT_BAG"] = "Reagent Bag"
L["INV_LOC_BANK"] = "Bank"
L["INV_LOC_WARBAND_BANK"] = "Warband Bank"
L["INV_LOC_OTHERS"] = "Others"
-- CLP Labels
L["CLP_LABEL_VISIBLE"] = "Hide"
L["CLP_LABEL_NAME"] = "Name"
L["CLP_LABEL_CLASS"] = "Class"
L["CLP_LABEL_REALM"] = "Realm"
L["CLP_LABEL_LEVEL"] = "Level"
L["CLP_LABEL_FACTION"] = "Faction"
L["CLP_LABEL_ZONE"] = "Zone"
L["CLP_LABEL_SUBZONE"] = "Sub Zone"
L["CLP_LABEL_ITEM_LEVEL"] = "Item Level"
L["CLP_LABEL_RV"] = "Raids Vault"
L["CLP_LABEL_DV"] = "Dungeons Vault"
L["CLP_LABEL_WV"] = "World Vault"
L["CLP_LABEL_M_SCORE"] = "M+ Score"
L["CLP_LABEL_PLAYED"] = "Played"
L["CLP_LABEL_GOLD"] = "Gold"
L["CLP_LABEL_CURRENCIES"] = "Currencies"
L["CLP_LABEL_PVP"] = "PvP"
L["CLP_LABEL_UPDATED"] = "Updated"
L["CLP_LABEL_OPERATION"] = "Operation"
-- CGP
L["CGP_BANNER"] = "Character"
L["CGP_ITEM_LEVEL"] = "Item Level"
L["CGP_ATTRIBUTES"] = "Attributes"
L["CGP_ENHANCEMENTS"] = "Enhancements"
L["CGP_STAT_STRENGTH"] = "Strength"
L["CGP_STAT_AGILITY"] = "Agility"
L["CGP_STAT_INTELLECT"] = "Intellect"
L["CGP_STAT_STAMINA"] = "Stamina"
L["CGP_STAT_ARMOR"] = "Armor"
L["CGP_STAT_CRITICAL_STRIKE"] = "Crit Strike"
L["CGP_STAT_HASTE"] = "Haste"
L["CGP_STAT_MASTERY"] = "Mastery"
L["CGP_STAT_VERSATILITY"] = "Versatility"
L["CGP_STAT_LIFESTEAL"] = "Lifesteal"
L["CGP_STAT_SPEED"] = "Speed"
L["CGP_STAT_AVOIDANCE"] = "Avoidance"
-- Confirm dialog
L["CT_CONFIRM_REMOVE_CHARACTER_DATA"] = "Delete all cached data for %s?\nThis data will be permanently lost."
L["CT_CONFIRM_Y"] = "Confirm"
L["CT_CONFIRM_N"] = "Cancel"

-- ====================================================================
-- 简体中文环境 (zhCN)
-- ====================================================================
if currentLocale == "zhCN" then
  L["CT_TITLE"] = "角色追踪"
  L["FB_FUNC"] = "战团角色追踪"
  L["FB_L1"] = "按住左键拖动: 自由调整按钮位置"
  L["FB_L2"] = "左键点击: 打开/关闭战团角色列表"
  L["FB_L3"] = "右键点击: 开启/关闭战团物品汇总"
  L["VT_TITLE"] = "宏伟宝库进度"
  L["VT_RAIDS"] = "团队副本"
  L["VT_DUNGEONS"] = "地下城"
  L["VT_DW"] = "地下堡/世界"
  L["VT_UNLOCKED"] = "已解锁"
  L["VT_LEVEL"] = "%d层"
  L["VT_LOCKED"] = "未开始"
  L["CHOOSE_CHARACTER"] = "角色选择"
  L["GEAR_DETAIL"] = "详细装备"
  L["CURR_TIP_L1"] = "暂无该角色的非战网共享货币数据"
  L["CURR_TIP_L2"] = "请切换登录该角色以同步数据"
  L["CURR_WEEKLY_LIMIT"] = " |cff0070dd(%d/%d) 每周|r"
  L["CURR_SEASON_LIMIT"] = " |cffff8000(%d/%d) 赛季|r"
  L["CURR_LIMIT"] = " |cffffd100(%d/%d)|r"
  L["INV_TITLE"] = "战团物品汇总"
  L["INV_LOADING"] = "加载中..."
  L["INV_SEARCH_TIP"] = "搜索..."
  L["INV_DETAIL"] = "|cffffd100物品存储明细:|r"
  L["INV_SRC_WARBAND"] = "|cff66bbff战团|r"
  L["INV_LOC_BAG"] = "背包"
  L["INV_LOC_REAGENT_BAG"] = "材料包"
  L["INV_LOC_BANK"] = "银行"
  L["INV_LOC_WARBAND_BANK"] = "战团银行"
  L["INV_LOC_OTHERS"] = "其他"
  -- CLP Labels
  L["CLP_LABEL_VISIBLE"] = "隐藏"
  L["CLP_LABEL_NAME"] = "名称"
  L["CLP_LABEL_CLASS"] = "职业"
  L["CLP_LABEL_REALM"] = "服务器"
  L["CLP_LABEL_LEVEL"] = "等级"
  L["CLP_LABEL_FACTION"] = "阵营"
  L["CLP_LABEL_ZONE"] = "地区"
  L["CLP_LABEL_SUBZONE"] = "区域"
  L["CLP_LABEL_ITEM_LEVEL"] = "装备等级"
  L["CLP_LABEL_RV"] = "团队副本"
  L["CLP_LABEL_DV"] = "地下城"
  L["CLP_LABEL_WV"] = "地下堡/世界"
  L["CLP_LABEL_M_SCORE"] = "大秘境分数"
  L["CLP_LABEL_PLAYED"] = "游戏时长"
  L["CLP_LABEL_GOLD"] = "金币"
  L["CLP_LABEL_CURRENCIES"] = "货币"
  L["CLP_LABEL_PVP"] = "PvP"
  L["CLP_LABEL_UPDATED"] = "更新时间"
  L["CLP_LABEL_OPERATION"] = "操作"
  -- CGP
  L["CGP_BANNER"] = "角色"
  L["CGP_ITEM_LEVEL"] = "物品等级"
  L["CGP_ATTRIBUTES"] = "属性"
  L["CGP_ENHANCEMENTS"] = "强化属性"
  L["CGP_STAT_STRENGTH"] = "力量"
  L["CGP_STAT_AGILITY"] = "敏捷"
  L["CGP_STAT_INTELLECT"] = "智力"
  L["CGP_STAT_STAMINA"] = "耐力"
  L["CGP_STAT_ARMOR"] = "护甲"
  L["CGP_STAT_CRITICAL_STRIKE"] = "暴击"
  L["CGP_STAT_HASTE"] = "急速"
  L["CGP_STAT_MASTERY"] = "精通"
  L["CGP_STAT_VERSATILITY"] = "全能"
  L["CGP_STAT_LIFESTEAL"] = "吸血"
  L["CGP_STAT_SPEED"] = "加速"
  L["CGP_STAT_AVOIDANCE"] = "闪避"
  -- Confirm dialog
  L["CT_CONFIRM_REMOVE_CHARACTER_DATA"] = "确定要清除角色 %s 的所有缓存数据吗？\n该操作执行后该角色的数据将无法恢复。"
  L["CT_CONFIRM_Y"] = "确定"
  L["CT_CONFIRM_N"] = "取消"
end
